# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    -   package-ecosystem: 'github-actions'
        directory: /
        schedule:
            interval: "daily"
            timezone: Asia/Tokyo
        assignees:
            - "hytsnbr"
        reviewers:
            - "hytsnbr"
        commit-message:
            prefix: update
            include: scope
        labels:
            - "dependabot"
        open-pull-requests-limit: 99

    -   package-ecosystem: "gradle"
        directory: /
        schedule:
            interval: "daily"
            timezone: Asia/Tokyo
        assignees:
            - "hytsnbr"
        reviewers:
            - "hytsnbr"
        commit-message:
            prefix: update
            include: scope
        labels:
            - "dependabot"
        open-pull-requests-limit: 99

    -   package-ecosystem: "gradle"
        directory: web/
        schedule:
            interval: "daily"
            timezone: Asia/Tokyo
        assignees:
            - "hytsnbr"
        reviewers:
            - "hytsnbr"
        commit-message:
            prefix: update
            include: scope
        labels:
            - "dependabot"
        open-pull-requests-limit: 99

    -   package-ecosystem: "gradle"
        directory: app/base-common/
        schedule:
            interval: "daily"
            timezone: Asia/Tokyo
        assignees:
            - "hytsnbr"
        reviewers:
            - "hytsnbr"
        commit-message:
            prefix: update
            include: scope
    labels:
        - "dependabot"
    open-pull-requests-limit: 99

        -   package-ecosystem: "gradle"
            directory: app/steam/
    schedule:
        interval: "daily"
        timezone: Asia/Tokyo
    assignees:
        - "hytsnbr"
        reviewers:
            - "hytsnbr"
    commit-message:
        prefix: update
        include: scope
        labels:
            - "dependabot"
        open-pull-requests-limit: 99

            -   package-ecosystem: "gradle"
                directory: app/steam-tool/
    schedule:
        interval: "daily"
        timezone: Asia/Tokyo
    assignees:
        - "hytsnbr"
        reviewers:
            - "hytsnbr"
        commit-message:
            prefix: update
            include: scope
        labels:
            - "dependabot"
        open-pull-requests-limit: 99

            -   package-ecosystem: "gradle"
                directory: app/todo-info/
                schedule:
                    interval: "daily"
                    timezone: Asia/Tokyo
                assignees:
                    - "hytsnbr"
                reviewers:
                    - "hytsnbr"
                commit-message:
                    prefix: update
                    include: scope
                labels:
                    - "dependabot"
                open-pull-requests-limit: 99

            -   package-ecosystem: "gradle"
                directory: app/zipcode/
                schedule:
                    interval: "daily"
                    timezone: Asia/Tokyo
                assignees:
                    - "hytsnbr"
                reviewers:
                    - "hytsnbr"
                commit-message:
                    prefix: update
                    include: scope
        labels:
            - "dependabot"
        open-pull-requests-limit: 99
