# Server
server:
  port: 8080
  servlet:
    context-path: /

spring:
  # Thymeleaf
  thymeleaf:
    mode: HTML
    cache: false
    enabled: true

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    # schema: classpath:database/schema.sql
    # data: classpath:database/data.sql

  # SQL
  sql:
    init:
      mode: always

# API
api:
  key:
    steam: op://VSCode/steam api key/value

  config:
    timeout:
      read: 10
      connection: 2
